services:
  db:
    image: postgres:15
    container_name: nexus3d_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nexus3d_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
    container_name: nexus3d_api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/nexus3d_db
    depends_on:
      - db
      - minio

  web:
    build:
      context: ./web-client
    container_name: nexus3d_web
    ports:
      - "3000:80"
    depends_on:
      - api

  minio:
    image: minio/minio
    container_name: nexus3d_minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
