version: "3.8"

services:
  db:
    image: postgres:15
    container_name: nexus3d_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nexus3d_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
    container_name: nexus3d_api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/nexus3d_db
    depends_on:
      - db

volumes:
  postgres_data:
